<?php
// echo "<title>Cetak Surat</title>";

$tgl=date('d-m-Y');
$waktu = date('d-m-Y H:i:s');
$tahun = date('Y');

$pdf = new FPDF(); //L = lanscape P= potrait
$pdf->SetTitle('Cetak Surat Peminjaman');
$pdf->SetAutoPageBreak(false);
foreach ($data as $row){
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->Image('./assets/images/icon/BPJS.png',7,1,70,50);
$pdf->Ln(30);
$pdf->SetFont('Arial','B',17);
$pdf->Cell(0,20,'BPJS Ketenagakerjaan Semarang Pemuda',0,1,'C');
$pdf->SetFont('Arial','',10);
$pdf->Cell(0,-8,'Jl. Pemuda No. 130 Semarang 50132, TELP: 024-3520279, 3588880, FAKS: 024-553712, 3585530',0,1,'C');
$pdf->SetFont('Arial','BU',12);
$pdf->Cell(0,40,'SURAT PEMINJAMAN ARSIP BPJS KETENAGAKERJAAN KANTOR WILAYAH',0,1,'C');
$pdf->SetFont('Arial','',12);
$pdf->Cell(190,-30,'Nomor : BPJS/ARSIP/'.$row['id_peminjam'] . '/KANWIL' , 0,1,'C');
$pdf->SetFont('Arial','',11);
$pdf->Cell(0,60,'Dengan dikeluarkannya surat ini, Saya telah menyetujui persyaratan dan telah mendapat izin untuk melakukan  ',0,1,'J');
$pdf->Cell(0,-45,'peminjaman arsip dengan detail peminjaman sebagai berikut :',0,1,'J');


$pdf->Ln(35);
$pdf->SetFont('Arial','',11);
/******** 1 ************/
$pdf->SetLeftMargin(65);
$pdf->Cell(100,10,'Nama Peminjam        :     ' .$row['nama_user'],0,1,'L');
/******** 2 ************/
$pdf->Cell(100,10,'NIK                             :     ' .$row['npp_user'],0,1,'L');


/******** 3 ************/
$pdf->Cell(100,10,'Jabatan                      :     ' .$row['jabatan'],0,1,'L');

///******** 4 ************/

$pdf->Cell(100,10,'Email                          :     ' .$row['email'],0,1,'L');

///******** 5 ************/
$pdf->Cell(100,10,'Tanggal Peminjaman :     ' .$row['tgl_peminjaman'],0,1,'L');

/******** 6 ************/
$pdf->Cell(100,10,'Jenis Voucher            :     ' .$row['jenis_voucher'],0,1,'L');

/******** 7 ************/
$pdf->Cell(100,10,'No Voucher                :     ' .$row['box']. ' - '.$row['rak'],0,1,'L');

///******** 8 ************/
// $pdf->Cell(5,10,'2. ',1,0,'L');
// $pdf->Cell(100,10,'NIK ',1,0,'L');
// $pdf->Cell(91,10,''.$row['npp_user'],1,1,'L');
// /******** 9 ************/
// $pdf->SetY(162);
// $pdf->Cell(5,10,'9. ',1,0,'L');
// $pdf->Cell(100,10,'Nomor Rekening',1,0,'L');
// $pdf->Cell(91,10,$row['npp_user'],1,1,'L');
// ///******** 10 ************/
// $pdf->SetY(172);
// $pdf->Cell(5,10,'10. ',1,0,'L');
// $pdf->Cell(100,10,'Lapsum',1,0,'L');
// $pdf->Cell(91,10,$row['npp_user'],1,1,'L');
/******** Tanda Tangan ************/
$pdf->SetLeftMargin(130);
$pdf->Ln(20);
$pdf->MultiCell(85,4,'Dikeluarkan di        : Semarang
Pada tanggal          : '.$tgl.'
__________________________',0,'L');
$pdf->SetFont('Arial','B',10);
$pdf->SetLeftMargin(0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(60, 3.5, 'Yang menyetujui',0,2,'C');
$pdf->Cell(60, 3.5, 'Penata Madya Kearsipan',0,2,'C');
$pdf->Ln(20);
$pdf->SetFont('Arial', 'U', 10);
$pdf->SetLeftMargin(130);
$pdf->Cell(60, 3.5, 'Agus Prasetyo, S.T',0,2,'C');
$pdf->SetFont('Arial', '', 10);


$pdf->SetFont('Arial', 'I', 8); 
$pdf->SetTextColor(0); 
$pdf->Cell(0, 90, "Generated by BPJS Ketenagakerjaan SiAR at ".$waktu." Copyright " . $tahun, '', 0, 'R'); 

}
$pdf->Output();
?>    